name: Arduino Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          Get-Location
          Get-ChildItem
          arduino-cli board list

      - name: Kill Arduino IDE
        run: |
          taskkill /IM arduino.exe /F || exit 0

      - name: Compile
        run: |
          arduino-cli compile --fqbn arduino:avr:uno .

      - name: Upload
        run: |
          arduino-cli upload -p COM4 --fqbn arduino:avr:uno .
